// <auto-generated />
using System;
using Comments.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Comments.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CommentsDbContext))]
    partial class CommentsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Comments.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OriginalTextFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TextFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 28, 23, 29, 0, 400, DateTimeKind.Unspecified),
                            Email = "www@gmail.com",
                            Text = "This is a great post!",
                            UserName = "Alice"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 29, 10, 10, 0, 0, DateTimeKind.Unspecified),
                            Email = "bob@mail.com",
                            Text = "I really enjoyed reading this.",
                            UserName = "Bob"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 12, 29, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            Email = "charlie@mail.com",
                            Text = "Very informative, thanks!",
                            UserName = "Charlie"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 12, 29, 10, 20, 0, 0, DateTimeKind.Unspecified),
                            Email = "diana@mail.com",
                            Text = "Could you share more details?",
                            UserName = "Diana"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 12, 29, 10, 25, 0, 0, DateTimeKind.Unspecified),
                            Email = "edward@mail.com",
                            Text = "This helped me a lot.",
                            UserName = "Edward"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 12, 29, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Email = "fiona@mail.com",
                            Text = "Clear and well written.",
                            UserName = "Fiona"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 12, 29, 10, 35, 0, 0, DateTimeKind.Unspecified),
                            Email = "george@mail.com",
                            Text = "I have a different opinion.",
                            UserName = "George"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 12, 29, 10, 40, 0, 0, DateTimeKind.Unspecified),
                            Email = "helen@mail.com",
                            Text = "Nice explanation!",
                            UserName = "Helen"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 12, 29, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            Email = "ian@mail.com",
                            Text = "Looking forward to the next post.",
                            UserName = "Ian"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 12, 29, 10, 50, 0, 0, DateTimeKind.Unspecified),
                            Email = "julia@mail.com",
                            Text = "This topic is very relevant.",
                            UserName = "Julia"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 12, 29, 10, 55, 0, 0, DateTimeKind.Unspecified),
                            Email = "kevin@mail.com",
                            Text = "Thanks for sharing!",
                            UserName = "Kevin"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 12, 29, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "laura@mail.com",
                            Text = "Good overview of the problem.",
                            UserName = "Laura"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 12, 29, 11, 5, 0, 0, DateTimeKind.Unspecified),
                            Email = "michael@mail.com",
                            Text = "I learned something new today.",
                            UserName = "Michael"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 12, 29, 11, 10, 0, 0, DateTimeKind.Unspecified),
                            Email = "nina@mail.com",
                            Text = "Well structured and easy to read.",
                            UserName = "Nina"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 12, 29, 11, 15, 0, 0, DateTimeKind.Unspecified),
                            Email = "oscar@mail.com",
                            Text = "Can you provide examples?",
                            UserName = "Oscar"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2025, 12, 29, 11, 20, 0, 0, DateTimeKind.Unspecified),
                            Email = "paul@mail.com",
                            Text = "This answered my question.",
                            UserName = "Paul"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2025, 12, 29, 11, 25, 0, 0, DateTimeKind.Unspecified),
                            Email = "andrey@mail.ru",
                            Text = "Отличная статья, спасибо!",
                            UserName = "Андрей"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2025, 12, 29, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            Email = "maria@mail.ru",
                            Text = "Очень полезная информация.",
                            UserName = "Мария"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2025, 12, 29, 11, 35, 0, 0, DateTimeKind.Unspecified),
                            Email = "ivan@mail.ru",
                            Text = "Полностью согласен с автором.",
                            UserName = "Иван"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2025, 12, 29, 11, 40, 0, 0, DateTimeKind.Unspecified),
                            Email = "olga@mail.ru",
                            Text = "Хорошо объяснено и понятно.",
                            UserName = "Ольга"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2025, 12, 29, 11, 45, 0, 0, DateTimeKind.Unspecified),
                            Email = "sergey@mail.ru",
                            Text = "Интересная тема для обсуждения.",
                            UserName = "Сергей"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2025, 12, 29, 11, 50, 0, 0, DateTimeKind.Unspecified),
                            Email = "kate@mail.ru",
                            Text = "Спасибо за подробное описание.",
                            UserName = "Екатерина"
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2025, 12, 29, 11, 55, 0, 0, DateTimeKind.Unspecified),
                            Email = "dmitry@mail.ru",
                            Text = "Было полезно прочитать.",
                            UserName = "Дмитрий"
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2025, 12, 29, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nataly@mail.ru",
                            Text = "Жду продолжения.",
                            UserName = "Наталья"
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2025, 12, 29, 12, 5, 0, 0, DateTimeKind.Unspecified),
                            Email = "alex@mail.ru",
                            Text = "Хороший пример реализации.",
                            UserName = "Алексей"
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2025, 12, 29, 12, 10, 0, 0, DateTimeKind.Unspecified),
                            Email = "irina@mail.ru",
                            Text = "Все разложено по полочкам.",
                            UserName = "Ирина"
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2025, 12, 29, 12, 15, 0, 0, DateTimeKind.Unspecified),
                            Email = "pavel@mail.ru",
                            Text = "Информация актуальна.",
                            UserName = "Павел"
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2025, 12, 29, 12, 20, 0, 0, DateTimeKind.Unspecified),
                            Email = "tatiana@mail.ru",
                            Text = "Спасибо, было интересно.",
                            UserName = "Татьяна"
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2025, 12, 29, 12, 25, 0, 0, DateTimeKind.Unspecified),
                            Email = "victor@mail.ru",
                            Text = "Хорошая подача материала.",
                            UserName = "Виктор"
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2025, 12, 29, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            Email = "elena@mail.ru",
                            Text = "Полезно для начинающих.",
                            UserName = "Елена"
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2025, 12, 30, 23, 29, 0, 0, DateTimeKind.Unspecified),
                            Email = "www@gmail.com",
                            ParentId = 1,
                            Text = "This topic is very relevant.",
                            UserName = "Alice"
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2025, 12, 30, 10, 10, 0, 0, DateTimeKind.Unspecified),
                            Email = "bob@mail.com",
                            ParentId = 1,
                            Text = "I really enjoyed reading this.",
                            UserName = "Bob"
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2025, 12, 30, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            Email = "charlie@mail.com",
                            ParentId = 1,
                            Text = "Very informative, thanks!",
                            UserName = "Charlie"
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2025, 12, 30, 10, 20, 0, 0, DateTimeKind.Unspecified),
                            Email = "diana@mail.com",
                            ParentId = 1,
                            Text = "Could you share more details?",
                            UserName = "Diana"
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2025, 12, 30, 10, 25, 0, 0, DateTimeKind.Unspecified),
                            Email = "edward@mail.com",
                            ParentId = 1,
                            Text = "This helped me a lot.",
                            UserName = "Edward"
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2025, 12, 30, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Email = "fiona@mail.com",
                            ParentId = 1,
                            Text = "Clear and well written.",
                            UserName = "Fiona"
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2025, 12, 30, 10, 35, 0, 0, DateTimeKind.Unspecified),
                            Email = "george@mail.com",
                            ParentId = 1,
                            Text = "I have a different opinion.",
                            UserName = "George"
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2025, 12, 30, 10, 40, 0, 0, DateTimeKind.Unspecified),
                            Email = "helen@mail.com",
                            ParentId = 1,
                            Text = "Nice explanation!",
                            UserName = "Helen"
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2025, 12, 30, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            Email = "ian@mail.com",
                            ParentId = 1,
                            Text = "Looking forward to the next post.",
                            UserName = "Ian"
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2025, 12, 30, 10, 50, 0, 0, DateTimeKind.Unspecified),
                            Email = "julia@mail.com",
                            ParentId = 1,
                            Text = "This topic is very relevant.",
                            UserName = "Julia"
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2025, 12, 30, 11, 45, 0, 0, DateTimeKind.Unspecified),
                            Email = "sergey@mail.ru",
                            ParentId = 2,
                            Text = "Интересная тема для обсуждения.",
                            UserName = "Сергей"
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2025, 12, 30, 11, 50, 0, 0, DateTimeKind.Unspecified),
                            Email = "kate@mail.ru",
                            ParentId = 2,
                            Text = "Спасибо за подробное описание.",
                            UserName = "Екатерина"
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2025, 12, 30, 11, 55, 0, 0, DateTimeKind.Unspecified),
                            Email = "dmitry@mail.ru",
                            ParentId = 2,
                            Text = "Было полезно прочитать.",
                            UserName = "Дмитрий"
                        });
                });

            modelBuilder.Entity("Comments.Models.Comment", b =>
                {
                    b.HasOne("Comments.Models.Comment", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Comments.Models.Comment", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
